sudo: required
services:
    - docker
before_install:
    - docker build -t akashmane15/client-test -f ./client/Dockerfile.dev ./client
scripts:
    - docker run -e CI=true akashmane15/client-test npm test

after_success:
    - docker build -t akashmane15/multi-client ./client
    - docker build -t akashmane15/multi-nginx ./nginx
    - docker build -t akashmane15/multi-server ./server
    - docker build -t akashmane15/multi-worker ./worker
    #Login to docker cli 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images & push to docker hub
    - docker push akashmane15/multi-client 
    - docker push akashmane15/multi-nginx 
    - docker push akashmane15/multi-server 
    - docker push akashmane15/multi-worker 


deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-south-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-748792653956
    bucker_path: docker-multi
    on:
        branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
      